/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.bo.PersonaBO;
import ec.edu.ups.bo.UsuarioBO;
import ec.edu.ups.entidad.Personas;
import ec.edu.ups.entidad.Usuarios;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;



/**
 *
 * @author user
 */
public final class GestionUsuarios extends javax.swing.JInternalFrame {

    private int id=0;
    private UsuarioBO usuariosBO;
    private PersonaBO personasBO;
    private Usuarios user;

    public GestionUsuarios(UsuarioBO usuariosBO,PersonaBO personasBO) {
        initComponents();
        this.usuariosBO=usuariosBO;
        this.personasBO=personasBO;
        this.user=null;
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code.The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param anio
     * @return
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        txtContra = new javax.swing.JPasswordField();
        lblNombre2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNombre3 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbID = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbAdmin = new javax.swing.JRadioButton();
        rbEmpleado = new javax.swing.JRadioButton();
        btnAgregarEmpleado = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Administrar Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblDireccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDireccion.setText("Rol:");

        lblNombre1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre1.setText("Contraseña: ");

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------------SELECCIONAR------------------------------", "EMPLEADO", "ADMINISTRADOR" }));
        cbxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRolActionPerformed(evt);
            }
        });

        lblNombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre2.setText("Cedula:");

        lblNombre3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre3.setText("Empleado:");

        txtEmpleado.setEditable(false);
        txtEmpleado.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblApellido))
                    .addComponent(lblNombre)
                    .addComponent(lblDireccion)
                    .addComponent(lblNombre2)
                    .addComponent(lblNombre3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtContra)
                    .addComponent(txtCedula)
                    .addComponent(txtEmpleado))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre2))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblApellido))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(0, 51, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("AGREGAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 51, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 51, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("MODIFICAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(0, 51, 255));
        btnListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 51, 255));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup2.add(rbID);
        rbID.setText("ID");

        buttonGroup2.add(rbNombre);
        rbNombre.setText("NOMBRE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbID)
                    .addComponent(rbNombre))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbID)
                .addGap(34, 34, 34)
                .addComponent(rbNombre)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Listar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(rbAdmin);
        rbAdmin.setText("ADMINISTRADOR");

        buttonGroup1.add(rbEmpleado);
        rbEmpleado.setText("EMPLEADO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAdmin)
                    .addComponent(rbEmpleado))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(rbEmpleado)
                .addGap(36, 36, 36))
        );

        btnAgregarEmpleado.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarEmpleado.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAgregarEmpleado.setText("AGREGAR EMPLEADO");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean validarCampos(){
    
    if(txtNombre.getText().equals("")||txtContra.getText().equals("")||cbxRol.getSelectedIndex()==0||txtCedula.getText().equals("")){
    JOptionPane.showMessageDialog(this, "CAMPOS VACIOS");
        return false;
    }else{
    
         return true;
    } 
    }
    public void limpiar() {
      txtNombre.setText("");
      txtContra.setText("");
      cbxRol.setSelectedItem(0);
      txtCedula.setEnabled(true);
      txtEmpleado.setEnabled(true);
      buttonGroup1.clearSelection();
    }

    public void cargarUsuariosTbl() {
       System.out.println(user);
          String p="";
        if(rbAdmin.isSelected()){
            p="ADMIN";
            System.out.println(p);
        }
        if (rbEmpleado.isSelected()){
            p="EMP";
            System.out.println(p);
        }
        
        if(p.equals("")){
        buttonGroup1.clearSelection();
        }
        if(user!=null&&p.equals("")){
            usuariosBO.listarUsuarios(tblUsuarios, user);//listamos todos
        }else if(user!=null&&p.equals("ADMIN")){
            //listamos usuarios administradores
            usuariosBO.listarUsuariosA(tblUsuarios, user);
            
        }else if(user!=null&&p.equals("EMP")){
          //listamos usuarios empleados
          usuariosBO.listarUsuariosG(tblUsuarios, user);
        }else{
        System.out.println("TABLA VACIA:USUARIOS");
        }
     
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         String mensaje="";
           
         String rol="";
         String encP="";
         String pass = "";
         
          if (cbxRol.getSelectedItem()=="ADMINISTRADOR") {
            rol="A";

        }
          
          if (cbxRol.getSelectedItem()=="EMPLEADO") {
            rol="G";
        } 
          System.out.println(rol);
        char[] pass1 = txtContra.getPassword();
        for (int i = 0; i < pass1.length; i++) {
            pass = pass + pass1[i];
        }
        try {
           encP= encript(pass);
        } catch (Exception ex) {
            System.out.println("ERROR ENCRIPTAR: "+ex.getMessage());
        }
           Usuarios u = new Usuarios();
        if (validarCampos()){
               u.setUsu_nombre(txtNombre.getText().trim());
               u.setUsu_contra(encP);
               u.setUsu_rol(rol.charAt(0));
              mensaje=usuariosBO.agregarUsuario(txtCedula.getText().trim(), u);
              JOptionPane.showMessageDialog(this, mensaje);
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

       String mensaje="";
           
         String rol="";
         String encP="";
         String pass = "";
         
          if (cbxRol.getSelectedItem()=="ADMINISTRADOR") {
            rol="A";

        }
          
          if (cbxRol.getSelectedItem()=="EMPLEADO") {
            rol="G";
        } 
          System.out.println(rol);
        char[] pass1 = txtContra.getPassword();
        for (int i = 0; i < pass1.length; i++) {
            pass = pass + pass1[i];
        }
        
           encP= encript(pass);
      
           System.out.println(""+encP);
        
           Usuarios u = new Usuarios();
        if (validarCampos()){
               u.setUsu_codigo(id);
               u.setUsu_nombre(txtNombre.getText().trim());
               u.setUsu_contra(encP);
               u.setUsu_rol(rol.charAt(0));
              mensaje=usuariosBO.actualizarUsuario(txtCedula.getText().trim(), u);
              JOptionPane.showMessageDialog(this, mensaje);
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     String mensaje="";
        System.out.println(id+" "+user);
        if(validarCampos()||id!=0){
            int d = JOptionPane.showConfirmDialog(this, "ESTA SEGURO DE ELIMINAR AL EMPLEADO " + txtNombre.getText());
            if (d == JOptionPane.YES_OPTION) {
               
                 mensaje = usuariosBO.eliminarUsuario(txtNombre.getText().trim(), user);
                 JOptionPane.showMessageDialog(this, mensaje);
               
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    public Usuarios getUser() {
        return user;
    }

    public void setUser(Usuarios user) {
        this.user = user;
    }

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
      cargarUsuariosTbl();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked

        int index = tblUsuarios.getSelectedRow();
        id = Integer.parseInt("" + tblUsuarios.getValueAt(index, 0));
        String usuario = "" + tblUsuarios.getValueAt(index, 1);
        String pass = "" + tblUsuarios.getValueAt(index, 2);
        String rol = "" + tblUsuarios.getValueAt(index, 3);
     if (rol.trim().equals("A")) {
            cbxRol.setSelectedItem(rol);

        } else if (rol.trim().equals("G")) {
            cbxRol.setSelectedItem(rol);
        } 
        txtNombre.setText(usuario);
        txtContra.setText(pass);
       
    }//GEN-LAST:event_tblUsuariosMouseClicked
   

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
      cargarUsuariosTbl();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String p="";
            if(rbID.isSelected()){
            p="ID";
                System.out.println(p);
            }
            if (rbNombre.isSelected()){
            p="NOMBRE";
             System.out.println(p);
            }
            
      
          Usuarios u= new Usuarios();
           String opcion = "";
          
            if(p.equals("ID")){
           opcion= JOptionPane.showInputDialog(null,"Ingrese ID");
           u.setUsu_codigo(id);
            }
            if(p.equals("NOMBRE")){
            opcion= JOptionPane.showInputDialog(null,"Ingrese Nombre");
           u.setUsu_nombre(opcion);
            }
            
            if(!"".equals(opcion)|| user!=null||!"".equals(p)){
            System.out.println(opcion+" "+p+" "+user);
            usuariosBO.buscarUsuario( u, tblUsuarios, p);
            }else{
             JOptionPane.showMessageDialog(this,"SELECCIONE TIPO DE BUSQUEDA");
            }
           
           
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRolActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
       if (!txtCedula.getText().isEmpty()){
           Personas per=personasBO.buscarPersonaO(txtCedula.getText().trim());
           txtCedula.setText(per.getPer_cedula());
           txtCedula.setEnabled(false);
           txtEmpleado.setEnabled(false);
           txtEmpleado.setText(per.getPer_nombre()+" "+per.getPer_apellidos());
       }else{
       JOptionPane.showMessageDialog(this, "LLENE EL CAMPO DE CEDULA");
       
       }
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed
Map<Character, Character> map = new HashMap<>();


    private void cargarLetras() {
        map.put('a', '*');
        map.put('b', '$');
        map.put('c', '?');
        map.put('d', '%');
        map.put('e', '#');
        map.put('f', '!');
        map.put('g', '¡');
        map.put('h', '¿');
        map.put('i', '}');
        map.put('j', '{');
        map.put('k', '[');
        map.put('l', ']');
        map.put('m', '|');
        map.put('n', '°');
        map.put('ñ', '=');
        map.put('o', '+');
        map.put('p', '-');
        map.put('q', ';');
        map.put('r', ',');
        map.put('s', '>');
        map.put('t', '<');
        map.put('u', 'A');
        map.put('v', 'B');
        map.put('w', 'C');
        map.put('x', 'f');
        map.put('y', 'x');
        map.put('z', 'p');
        map.put(' ', 'd');
        map.put('A', '&');
        map.put('B', '0');
        map.put('C', '1');
        map.put('D', '2');
        map.put('E', '3');
        map.put('F', '4');
        map.put('G', '5');
        map.put('H', '6');
        map.put('I', '7');
        map.put('J', '8');
        map.put('K', '9');
        map.put('L', 'ñ');
        map.put('M', 'y');
        map.put('N', 'Y');
        map.put('Ñ', '♠');
        map.put('O', 'z');
        map.put('P', 'Z');
        map.put('Q', 'X');
        map.put('R', 'W');
        map.put('S', 'w');
        map.put('T', 'J');
        map.put('U', 'j');
        map.put('V', 'Ñ');
        map.put('W', 'g');
        map.put('X', 'G');
        map.put('Y', 'P');
        map.put('Z', 'F');

    }

   private void cargarNumeros() {
        map.put('1', 'v');
        map.put('2', '♦');
        map.put('3', 's');
        map.put('4', 'E');
        map.put('5', 'k');
        map.put('6', '@');
        map.put('7', '☻');
        map.put('8', '↑');
        map.put('9', '↨');
        map.put('0', 'a');
    }

    private String encript(String cadena) {
        String encript = "";
        cargarLetras();
        cargarNumeros();
        for (int i = 0; i < cadena.length(); i++) {
            for (Map.Entry<Character, Character> entry : map.entrySet()) {
                char c = cadena.charAt(i);
        
                if (c==entry.getValue()) {

                    encript += entry.getKey();

                }

            }
        }
        return encript;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbEmpleado;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
