/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.bo.ServiciosBO;
import ec.edu.ups.bo.UsuarioBO;
import ec.edu.ups.entidad.Personas;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author user
 */
public final class GestionCitas extends javax.swing.JInternalFrame {

    private int id;
    private int idCliente;
    private int idOdonto;
    private ServiciosBO serviciosBO;
    private UsuarioBO usuariosBO;
    public GestionCitas(ServiciosBO serviciosBO , UsuarioBO usuariosBO) {
        initComponents();
    this.serviciosBO=serviciosBO;
    this.usuariosBO=usuariosBO;
       
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code.The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param anio
     * @return
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendarBeanInfo1 = new com.toedter.calendar.JCalendarBeanInfo();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jCalendarTheme1 = new com.toedter.plaf.JCalendarTheme();
        jPanel5 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        btnOd = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        dateFecha = new com.toedter.calendar.JDateChooser();
        lblCliente1 = new javax.swing.JLabel();
        lblCliente2 = new javax.swing.JLabel();
        cbxHora = new javax.swing.JComboBox<>();
        txtCedO = new javax.swing.JTextField();
        txtCedClient = new javax.swing.JTextField();
        txtOdont = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbFecha = new javax.swing.JRadioButton();
        rbCliente = new javax.swing.JRadioButton();
        rbDesac = new javax.swing.JRadioButton();

        setClosable(true);
        setResizable(true);
        setTitle("Administrar Citas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Citas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        lblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNombre.setText("Odontólogo:");

        lblCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        btnOd.setText("ASIGNAR");
        btnOd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdActionPerformed(evt);
            }
        });

        btnCliente.setText("ASIGNAR");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        dateFecha.setFocusTraversalPolicyProvider(true);
        dateFecha.setFocusable(false);
        dateFecha.setMaxSelectableDate(new java.util.Date(253370786469000L));

        lblCliente1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCliente1.setText("Fecha:");

        lblCliente2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCliente2.setText("Hora:");

        cbxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------SELECCIONAR---------", "08:00-09:30", "09:30-11:00", "11:00-12:30", "14:00-15:30", "15:30-17:00", "17:00-18:30", "18:30-20:00", "20:00-21:30" }));
        cbxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHoraActionPerformed(evt);
            }
        });

        txtCedO.setEnabled(false);
        txtCedO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedOActionPerformed(evt);
            }
        });

        txtCedClient.setEnabled(false);
        txtCedClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedClientActionPerformed(evt);
            }
        });

        txtOdont.setEnabled(false);
        txtOdont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOdontActionPerformed(evt);
            }
        });

        txtCliente.setEnabled(false);
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblCliente)
                    .addComponent(lblCliente1)
                    .addComponent(lblCliente2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedClient, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtCedO))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtOdont, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(btnOd))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCliente))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxHora, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(btnOd)
                    .addComponent(txtCedO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOdont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtCedClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente1)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(0, 51, 255));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("AGREGAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 51, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 51, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("MODIFICAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(0, 51, 255));
        btnListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("BUSCAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 255));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar1.setBackground(new java.awt.Color(0, 51, 255));
        btnListar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListar1.setForeground(new java.awt.Color(255, 255, 255));
        btnListar1.setText("LISTAR");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar1)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Citas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(rbFecha);
        rbFecha.setSelected(true);
        rbFecha.setText("FECHA");
        rbFecha.setBorder(new javax.swing.border.MatteBorder(null));
        rbFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        rbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCliente);
        rbCliente.setText("CLIENTE");
        rbCliente.setBorder(new javax.swing.border.MatteBorder(null));
        rbCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        rbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDesac);
        rbDesac.setText("CANCELADAS");
        rbDesac.setBorder(new javax.swing.border.MatteBorder(null));
        rbDesac.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        rbDesac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbFecha)
                            .addComponent(rbDesac))
                        .addGap(0, 222, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDesac)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //  Metodo el cual cambia el formato de la fecha
    public String formatoFecha(Date date){
        SimpleDateFormat formato_fecha = new SimpleDateFormat("YYYY");
        return formato_fecha.format(date) ;
   
   
   }
    public void limpiar() {
     txtCedO.setText("");
     txtCedClient.setText("");
     dateFecha.setCalendar(null);
     cbxHora.setSelectedIndex(0);
     txtOdont.setText("");
     txtCliente.setText("");
     buttonGroup1.clearSelection();
     idCliente=0;
     idOdonto=0;
    }

    public boolean validarCampos() {
     
     if( txtCedO.getText().isEmpty()||
             txtCedClient.getText().isEmpty()||
             dateFecha.getCalendar()==null||
             txtOdont.getText().isEmpty()||
             txtCliente.getText().isEmpty()||id==0||cbxHora.getSelectedIndex()==0)

     {
           JOptionPane.showMessageDialog(this, "CAMPOS VACIOS");
     return false;
     
     }else{
     return true;
     }

    }
    public void configDate(){
        //Metodo por el cual valida la seleccion de JCalendar
    int nMeses=1;
    Calendar calendar =Calendar.getInstance();
    Date fechaActual = new Date();
    calendar.setTime(fechaActual);
    calendar.add(Calendar.MONTH, nMeses);
    Date fechaMaxima=calendar.getTime();
    dateFecha.setDateFormatString("dd/MM/yyyy");
    dateFecha.setSelectableDateRange(fechaActual, fechaMaxima);
    
    }
    public void cargarCitasTbl() {

    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      if(validarCampos()){
        
          
      
      }
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (validarCampos()) {
            /*
                Tarifa tarifa1=null;
        for (Tarifa tarifa : controladorTarifa.tarifas()) {
                tarifa1=tarifa;
            }
             ClienteFijo cliente = new ClienteFijo();
            cliente.setTipoVehivulo(cbxAutomovil.getSelectedItem().toString().trim());
            cliente.setTipoTarifa(cbxTarifa.getSelectedItem().toString().trim());
            cliente.setAbono(Double.parseDouble(txtAbono.getText().trim()));
            cliente.setCedula(txtCedula.getText().trim());
            cliente.setNombre(txtNombre.getText().trim()); cliente.setApellido(txtApellido.getText().trim());
            cliente.setDireccion(txtDireccion.getText().trim());
            cliente.setTlf(txtTelefono.getText().trim());
            
          cliente.setFechaExpiracion(calcularFechaExpiracionPago(Double.parseDouble(txtAbono.getText().trim()),cliente,tarifa1));
          
          cliente.setAbono(calcularSaldoAbono (Double.parseDouble(txtAbono.getText().trim()),cliente,tarifa1));
          
          cliente.setEspacioParqueo( Integer.parseInt(cbxEspacioAsignar.getSelectedItem().toString().trim()));
             
          double multa= controladorClienteFijo.generarMulta(cliente);
               cliente.setMulta(multa);
               
                   if(cliente.getMulta()!=0){
               Ingresos ingreso = new Ingresos();
            Calendar fh= Calendar.getInstance();
            ingreso.setFechaHora(fh);
            ingreso.setDescripcion(" Paga multa : Cliente "+cliente.getNombre()+" "+cliente.getApellido()+ " con CI:  "+cliente.getCedula()+"");
            ingreso.setIngreso(cliente.getMulta());
            controladorIngreso.crear(ingreso);
               }
        if(controladorClienteFijo.actualizar(cliente)){
            Ingresos ingreso = new Ingresos();
            Calendar fh= Calendar.getInstance();
            ingreso.setFechaHora(fh);
            ingreso.setDescripcion(" Cliente Abona "+cliente.getNombre()+" "+cliente.getApellido()+ " con CI:  "+cliente.getCedula());
            ingreso.setIngreso(Double.parseDouble(txtAbono.getText().trim()));
            controladorIngreso.crear(ingreso);
            controladorEspacios.AsignarEspacio(Integer.parseInt(txtEspActual.getText().trim()), "");
            if(controladorEspacios.AsignarEspacio(Integer.parseInt(cbxEspacioAsignar.getSelectedItem().toString().trim()), txtCedula.getText().trim())){
                
          }
                
                    JOptionPane.showMessageDialog(this, "Datos actualizados con exito");
              
        }
        cargarCbxEspaciosDisp();
        cargarClientesFijosTbl();
        
             */
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        /*if(validarCampos()){
             int d = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar el cliente con cedula " + txtCedula.getText().trim());
        if (d == JOptionPane.YES_OPTION) {
     
       
        ClienteFijo c =controladorClienteFijo.buscar(id);
        
        if(controladorClienteFijo.eliminar(c)){
           
                controladorEspacios.AsignarEspacio(Integer.parseInt(txtEspActual.getText().trim()), "");
               
           
             JOptionPane.showMessageDialog(this, "eliminado exitosamente");
        }else{
         JOptionPane.showMessageDialog(this, "no se pudo eliminar ERROR");
        }
        }
       
       }*/
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        /* cargarCbxEspaciosDisp();        
    cargarClientesFijosTbl();*/
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitasMouseClicked

        int index = tblCitas.getSelectedRow();
        id = Integer.parseInt("" + tblCitas.getValueAt(index, 0));
        String cedula = "" + tblCitas.getValueAt(index, 1);
        String nombre = "" + tblCitas.getValueAt(index, 2);
        String apellido = "" + tblCitas.getValueAt(index, 3);
        String direccion = "" + tblCitas.getValueAt(index, 4);
        String telefono = "" + tblCitas.getValueAt(index, 5);
        String tipoVehiculo = "" + tblCitas.getValueAt(index, 6);
        String tipoTarifa = "" + tblCitas.getValueAt(index, 7);
        double abono = Double.parseDouble("" + tblCitas.getValueAt(index, 8));

    }//GEN-LAST:event_tblCitasMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       configDate();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListar1ActionPerformed

    private void cbxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxHoraActionPerformed

    private void txtCedClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedClientActionPerformed

    private void rbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFechaActionPerformed

    private void rbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteActionPerformed

    private void rbDesacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDesacActionPerformed

    private void txtCedOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedOActionPerformed

    private void txtOdontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOdontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOdontActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnOdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdActionPerformed
     
            String opcion = "";
            opcion= JOptionPane.showInputDialog(null,"Ingrese Cedula");
           Personas p= new Personas();
          if(!"".equals(opcion)){
           p=usuariosBO.buscarPeraona(opcion.trim());
          }else{
              JOptionPane.showMessageDialog(this, "CAMPO NULO");
          }

       if(p!=null){
       if(p.getPer_rol()=='O'){
         idOdonto = p.getPer_codigo();
         txtCedO.setText(p.getPer_cedula());
         txtOdont.setText(p.getPer_nombre()+" "+p.getPer_apellidos());
         JOptionPane.showMessageDialog(this, "ODONTOLOGO ASIGNADO CORRECTAMENTE");
         }else{
              JOptionPane.showMessageDialog(this, "DEBE ASIGNAR UN ODONTOLOGO ");
          }
         }else{
        JOptionPane.showMessageDialog(this, "NO SE ENCONTRO A LA PERSONA");
       
              }
     
    }//GEN-LAST:event_btnOdActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
   
            String opcion = "";
            opcion= JOptionPane.showInputDialog(null,"Ingrese Cedula");
           Personas p= new Personas();
          if(!"".equals(opcion)){
           p=usuariosBO.buscarPeraona(opcion.trim());
          }else{
              JOptionPane.showMessageDialog(this, "CAMPO NULO");
          }
       if(p!=null){
       if(p.getPer_rol()=='C'){
         idCliente = p.getPer_codigo();
         txtCedClient.setText(p.getPer_cedula());
         txtCliente.setText(p.getPer_nombre()+" "+p.getPer_apellidos());
         JOptionPane.showMessageDialog(this, "CLIENTE ASIGNADO CORRECTAMENTE");
         }else{
              JOptionPane.showMessageDialog(this, "DEBE ASIGNAR UN CLIENTE ");
          }
         }else{
        JOptionPane.showMessageDialog(this, "NO SE ENCONTRO A LA PERSONA");
       
              }
  
    }//GEN-LAST:event_btnClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar1;
    private javax.swing.JButton btnOd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxHora;
    private com.toedter.calendar.JDateChooser dateFecha;
    private com.toedter.calendar.JCalendarBeanInfo jCalendarBeanInfo1;
    private com.toedter.plaf.JCalendarTheme jCalendarTheme1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblCliente2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbDesac;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTextField txtCedClient;
    private javax.swing.JTextField txtCedO;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtOdont;
    // End of variables declaration//GEN-END:variables
}
