/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.bo.PersonaBO;
import ec.edu.ups.bo.ServiciosBO;
import ec.edu.ups.bo.UsuarioBO;
import ec.edu.ups.dao.PersonaDAO;
import ec.edu.ups.dao.ServiciosDAO;
import ec.edu.ups.dao.UsuarioDAO;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class VentanaPrincipal extends javax.swing.JFrame {

    private final VentanaIniciarSesion ventanaIniciarSesion;
    private final GestionUsuarios gestionUsuarios;
    private final GestionEmpleados gestionEmpleados;
    private final GestionClientes gestionClientes;
    private final GestionServicios gestionservicios;
    private final GestionCitas gestionCitas;
    private final FacturaClientes facturaClientes;
    
    
    private final PersonaBO pClienteBO;
    private final UsuarioBO usuarioBO ;
    private final ServiciosBO servicioBO;
    
    private final PersonaDAO personaClienteDAO;
    private final UsuarioDAO usuarioDAO;
    private final ServiciosDAO servicioDAO;
    
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(VentanaPrincipal.MAXIMIZED_BOTH);
        usuarioDAO= new UsuarioDAO();
        servicioDAO = new ServiciosDAO();
        usuarioBO= new UsuarioBO(usuarioDAO);
        servicioBO = new ServiciosBO(servicioDAO);
        personaClienteDAO=new PersonaDAO();
        pClienteBO=new PersonaBO(personaClienteDAO);
        gestionClientes = new GestionClientes(pClienteBO);
        gestionEmpleados = new GestionEmpleados(pClienteBO);
        gestionUsuarios = new GestionUsuarios(usuarioBO,pClienteBO);
        gestionservicios = new GestionServicios(servicioBO);
        facturaClientes = new FacturaClientes();
        gestionCitas = new GestionCitas(servicioBO,usuarioBO);
        ventanaIniciarSesion = new VentanaIniciarSesion(this,usuarioBO,gestionClientes
        ,gestionEmpleados,gestionUsuarios,gestionservicios);
   
       
       
        //Mostramos el Item de Inicio de Sesion
        iniciarSesionjMenuItem.setVisible(true);
        //Ocultamos los menus para usuario no logeado.
        CitasMenu.setVisible(false);
        ClientesMenu.setVisible(false);
        EmpleadosMenu.setVisible(false);
        FacturasMenu.setVisible(false);
        cerrarSesionJmenuItem.setVisible(false);
        nameUserMenu.setVisible(false);
        Usuariosmenu.setVisible(false);
        ServiciosMenu.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        InicioMenu = new javax.swing.JMenu();
        iniciarSesionjMenuItem = new javax.swing.JMenuItem();
        cerrarSesionJmenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        ClientesMenu = new javax.swing.JMenu();
        clientesjMenuItem = new javax.swing.JMenuItem();
        EmpleadosMenu = new javax.swing.JMenu();
        EmpleadosjMenuItem = new javax.swing.JMenuItem();
        ServiciosMenu = new javax.swing.JMenu();
        ServicioMenuItem = new javax.swing.JMenuItem();
        CitasMenu = new javax.swing.JMenu();
        CitasjMenuItem = new javax.swing.JMenuItem();
        FacturasMenu = new javax.swing.JMenu();
        FacturasjMenuItem = new javax.swing.JMenuItem();
        Usuariosmenu = new javax.swing.JMenu();
        UsuariosjMenuItem = new javax.swing.JMenuItem();
        nameUserMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InicioMenu.setMnemonic('f');
        InicioMenu.setText("Inicio");

        iniciarSesionjMenuItem.setText("Iniciar Sesion");
        iniciarSesionjMenuItem.setName("iniciarSesionmenuItem"); // NOI18N
        iniciarSesionjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionjMenuItemActionPerformed(evt);
            }
        });
        InicioMenu.add(iniciarSesionjMenuItem);

        cerrarSesionJmenuItem.setText("Cerrar Sesion");
        cerrarSesionJmenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionJmenuItemActionPerformed(evt);
            }
        });
        InicioMenu.add(cerrarSesionJmenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir ");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        InicioMenu.add(exitMenuItem);

        menuBar.add(InicioMenu);

        ClientesMenu.setText("Clientes");

        clientesjMenuItem.setText("Administrar Clientes");
        clientesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesjMenuItemActionPerformed(evt);
            }
        });
        ClientesMenu.add(clientesjMenuItem);

        menuBar.add(ClientesMenu);

        EmpleadosMenu.setText("Empleados");

        EmpleadosjMenuItem.setText("Administrar Empleados");
        EmpleadosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosjMenuItemActionPerformed(evt);
            }
        });
        EmpleadosMenu.add(EmpleadosjMenuItem);

        menuBar.add(EmpleadosMenu);

        ServiciosMenu.setText("Servicios");

        ServicioMenuItem.setText("Administrar Servicio");
        ServicioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioMenuItemActionPerformed(evt);
            }
        });
        ServiciosMenu.add(ServicioMenuItem);

        menuBar.add(ServiciosMenu);

        CitasMenu.setText("Citas");

        CitasjMenuItem.setText("Administrar Citas");
        CitasjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitasjMenuItemActionPerformed(evt);
            }
        });
        CitasMenu.add(CitasjMenuItem);

        menuBar.add(CitasMenu);

        FacturasMenu.setText("Facturas");

        FacturasjMenuItem.setText("Generar Factura");
        FacturasjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasjMenuItemActionPerformed(evt);
            }
        });
        FacturasMenu.add(FacturasjMenuItem);

        menuBar.add(FacturasMenu);

        Usuariosmenu.setText("Usuarios");

        UsuariosjMenuItem.setText("Administrar Usuarios");
        UsuariosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosjMenuItemActionPerformed(evt);
            }
        });
        Usuariosmenu.add(UsuariosjMenuItem);

        menuBar.add(Usuariosmenu);

        nameUserMenu.setText("NombreUsuario");
        menuBar.add(nameUserMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void centrar(JInternalFrame ventana, JDesktopPane desktop){
   int x= (desktop.getWidth()/2)-(ventana.getWidth()/2);
   int y = (desktop.getHeight()/2)-(ventana.getHeight()/2);
   
   if(ventana.isShowing()){
    ventana.setLocation(x, y);
    ventana.show();
   }
   }
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void clientesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesjMenuItemActionPerformed

        desktopPane.add(gestionClientes);
       
          gestionClientes.setVisible(true);

    }//GEN-LAST:event_clientesjMenuItemActionPerformed

    private void EmpleadosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosjMenuItemActionPerformed
        desktopPane.add(gestionEmpleados);
       
        gestionEmpleados.setVisible(true);
    }//GEN-LAST:event_EmpleadosjMenuItemActionPerformed

    private void FacturasjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasjMenuItemActionPerformed
        desktopPane.add(facturaClientes);
        
        facturaClientes.setVisible(true);
    }//GEN-LAST:event_FacturasjMenuItemActionPerformed

    private void iniciarSesionjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionjMenuItemActionPerformed
        desktopPane.add(ventanaIniciarSesion);
        
        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_iniciarSesionjMenuItemActionPerformed

    private void UsuariosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosjMenuItemActionPerformed
      desktopPane.add(gestionUsuarios);
        
        gestionUsuarios.setVisible(true);
    }//GEN-LAST:event_UsuariosjMenuItemActionPerformed

    private void ServicioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioMenuItemActionPerformed
        desktopPane.add(gestionservicios);
        
        gestionservicios.setVisible(true);
    }//GEN-LAST:event_ServicioMenuItemActionPerformed

    private void CitasjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitasjMenuItemActionPerformed
        desktopPane.add(gestionCitas);
        
        gestionCitas.setVisible(true);
    }//GEN-LAST:event_CitasjMenuItemActionPerformed

    private void cerrarSesionJmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionJmenuItemActionPerformed
     getCitasMenu().setVisible(false);
     this.getCerrarSesionJmenuItem().setVisible(false);
     getClientesMenu().setVisible(false);
     getEmpleadosMenu().setVisible(false);
     getFacturasMenu().setVisible(false);
     getServiciosMenu().setVisible(false);
     getNameUserMenu().setVisible(false);
        
     this.getIniciarSesionjMenuItem().setVisible(true);
     getUsuariosmenu().setVisible(false);
    }//GEN-LAST:event_cerrarSesionJmenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public JMenu getCitasMenu() {
        return CitasMenu;
    }

    public void setCitasMenu(JMenu CitasMenu) {
        this.CitasMenu = CitasMenu;
    }

    public JMenuItem getCitasjMenuItem() {
        return CitasjMenuItem;
    }

    public void setCitasjMenuItem(JMenuItem CitasjMenuItem) {
        this.CitasjMenuItem = CitasjMenuItem;
    }

    public JMenu getClientesMenu() {
        return ClientesMenu;
    }

    public void setClientesMenu(JMenu ClientesMenu) {
        this.ClientesMenu = ClientesMenu;
    }

    public JMenu getEmpleadosMenu() {
        return EmpleadosMenu;
    }

    public void setEmpleadosMenu(JMenu EmpleadosMenu) {
        this.EmpleadosMenu = EmpleadosMenu;
    }

    public JMenuItem getEmpleadosjMenuItem() {
        return EmpleadosjMenuItem;
    }

    public void setEmpleadosjMenuItem(JMenuItem EmpleadosjMenuItem) {
        this.EmpleadosjMenuItem = EmpleadosjMenuItem;
    }

    public JMenu getFacturasMenu() {
        return FacturasMenu;
    }

    public void setFacturasMenu(JMenu FacturasMenu) {
        this.FacturasMenu = FacturasMenu;
    }

    public JMenuItem getFacturasjMenuItem() {
        return FacturasjMenuItem;
    }

    public void setFacturasjMenuItem(JMenuItem FacturasjMenuItem) {
        this.FacturasjMenuItem = FacturasjMenuItem;
    }

    public JMenu getInicioMenu() {
        return InicioMenu;
    }

    public void setInicioMenu(JMenu InicioMenu) {
        this.InicioMenu = InicioMenu;
    }

    public JMenuItem getCerrarSesionjMenuItem() {
        return iniciarSesionjMenuItem;
    }

    public void setCerrarSesionjMenuItem(JMenuItem cerrarSesionjMenuItem) {
        this.iniciarSesionjMenuItem = cerrarSesionjMenuItem;
    }

    public JMenuItem getClientesjMenuItem() {
        return clientesjMenuItem;
    }

    public void setClientesjMenuItem(JMenuItem clientesjMenuItem) {
        this.clientesjMenuItem = clientesjMenuItem;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public void setExitMenuItem(JMenuItem exitMenuItem) {
        this.exitMenuItem = exitMenuItem;
    }

    public JMenuItem getjMenuItem2() {
        return cerrarSesionJmenuItem;
    }

    public void setjMenuItem2(JMenuItem jMenuItem2) {
        this.cerrarSesionJmenuItem = jMenuItem2;
    }

    public JMenu getNameUserMenu() {
        return nameUserMenu;
    }

    public void setNameUserMenu(JMenu nameUserMenu) {
        this.nameUserMenu = nameUserMenu;
    }

    public JMenu getUsuariosmenu() {
        return Usuariosmenu;
    }

    public void setUsuariosmenu(JMenu Usuariosmenu) {
        this.Usuariosmenu = Usuariosmenu;
    }

    public JMenuItem getUsuariosjMenuItem() {
        return UsuariosjMenuItem;
    }

    public void setUsuariosjMenuItem(JMenuItem UsuariosjMenuItem) {
        this.UsuariosjMenuItem = UsuariosjMenuItem;
    }

    public JMenuItem getCerrarSesionJmenuItem() {
        return cerrarSesionJmenuItem;
    }

    public void setCerrarSesionJmenuItem(JMenuItem cerrarSesionJmenuItem) {
        this.cerrarSesionJmenuItem = cerrarSesionJmenuItem;
    }

    public JMenuItem getIniciarSesionjMenuItem() {
        return iniciarSesionjMenuItem;
    }

    public void setIniciarSesionjMenuItem(JMenuItem iniciarSesionjMenuItem) {
        this.iniciarSesionjMenuItem = iniciarSesionjMenuItem;
    }

    public JMenuItem getServicioMenuItem() {
        return ServicioMenuItem;
    }

    public void setServicioMenuItem(JMenuItem ServicioMenuItem) {
        this.ServicioMenuItem = ServicioMenuItem;
    }

    public JMenu getServiciosMenu() {
        return ServiciosMenu;
    }

    public void setServiciosMenu(JMenu ServiciosMenu) {
        this.ServiciosMenu = ServiciosMenu;
    }
 public JDesktopPane desktopP (){
 
 
        return desktopPane;
 
 
 }

    public VentanaIniciarSesion getVentanaIniciarSesion() {
        return ventanaIniciarSesion;
    }

    public GestionUsuarios getGestionUsuarios() {
        return gestionUsuarios;
    }

    public GestionEmpleados getGestionEmpleados() {
        return gestionEmpleados;
    }

    public GestionClientes getGestionClientes() {
        return gestionClientes;
    }

    public GestionServicios getGestionservicios() {
        return gestionservicios;
    }

    public GestionCitas getGestionCitas() {
        return gestionCitas;
    }

    public FacturaClientes getFacturaClientes() {
        return facturaClientes;
    }

    public PersonaBO getpClienteBO() {
        return pClienteBO;
    }

    public UsuarioBO getUsuarioBO() {
        return usuarioBO;
    }

    public PersonaDAO getPersonaClienteDAO() {
        return personaClienteDAO;
    }

    public UsuarioDAO getUsuarioDAO() {
        return usuarioDAO;
    }

    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CitasMenu;
    private javax.swing.JMenuItem CitasjMenuItem;
    private javax.swing.JMenu ClientesMenu;
    private javax.swing.JMenu EmpleadosMenu;
    private javax.swing.JMenuItem EmpleadosjMenuItem;
    private javax.swing.JMenu FacturasMenu;
    private javax.swing.JMenuItem FacturasjMenuItem;
    private javax.swing.JMenu InicioMenu;
    private javax.swing.JMenuItem ServicioMenuItem;
    private javax.swing.JMenu ServiciosMenu;
    private javax.swing.JMenuItem UsuariosjMenuItem;
    private javax.swing.JMenu Usuariosmenu;
    private javax.swing.JMenuItem cerrarSesionJmenuItem;
    private javax.swing.JMenuItem clientesjMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem iniciarSesionjMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu nameUserMenu;
    // End of variables declaration//GEN-END:variables

}
