/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;



import ec.edu.ups.bo.UsuarioBO;
import ec.edu.ups.entidad.Usuarios;
import java.security.Key;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author Juanc
 */
public final class VentanaIniciarSesion extends javax.swing.JInternalFrame {

    private VentanaPrincipal ventanaPrincipal;
    
    private Usuarios user;
    
    private UsuarioBO usuarioBO;
    
    private GestionClientes gestionClientes;
     
    private GestionEmpleados gestionEmpleados;
    
    private GestionUsuarios gestionUsuarios;
    
    private GestionServicios gestionServicios;
    /**
     * Creates new form VentanaIniciarSesion
     *
     * @param ventanaPrincipal
     * @param usuarioBO
     * @param gestionClientes
     * @param gestionEmpleados
     * @param gestionUsuarios
     * @param gestionServicios
     *
     */
   
    public VentanaIniciarSesion(VentanaPrincipal ventanaPrincipal, UsuarioBO usuarioBO, GestionClientes gestionClientes,
            GestionEmpleados gestionEmpleados,GestionUsuarios gestionUsuarios,GestionServicios gestionServicios) {
        initComponents();
       
         user=new Usuarios();
        this.ventanaPrincipal = ventanaPrincipal;
        this.gestionClientes = gestionClientes;
        this.usuarioBO=usuarioBO;
        this.gestionEmpleados=gestionEmpleados;
        this.gestionUsuarios=gestionUsuarios;
        this.gestionServicios=gestionServicios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setClosable(true);
        setForeground(java.awt.Color.black);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblCorreo.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Usuario: ");

        lblContra.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lblContra.setForeground(new java.awt.Color(255, 255, 255));
        lblContra.setText("Contraseña:");

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIAR SESION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblContra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarSesion)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContra)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnIniciarSesion)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//private static String  ENCRYPT_KEY="clave-compartida-no-reveloar-nunca";

//private static String encript(String text) throws Exception {	
//	Key aesKey = new SecretKeySpec(ENCRYPT_KEY.getBytes(), "AES");
//
//	Cipher cipher = Cipher.getInstance("AES");
//	cipher.init(Cipher.ENCRYPT_MODE, aesKey);
//
//	byte[] encrypted = cipher.doFinal(text.getBytes());
//		
//	return Base64.encodeBytes(encrypted);
//	}
//
//private static String decrypt(String encrypted) throws Exception {
//	byte[] encryptedBytes=Base64.decode( encrypted.replace("\n", "") );
//		
//	Key aesKey = new SecretKeySpec(ENCRYPT_KEY.getBytes(), "AES");
//
//	Cipher cipher = Cipher.getInstance("AES");
//	cipher.init(Cipher.DECRYPT_MODE, aesKey);
//
//	String decrypted = new String(cipher.doFinal(encryptedBytes));
//        
//	return decrypted;
//	
//
//}
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
      
            //
            
            String pass = "";
            char[] pass1 = txtPass.getPassword();
            for (int i = 0; i < pass1.length; i++) {
                pass = pass + pass1[i];
            }
            String contra="";
              try {
            contra=encript(pass);
            
              } catch (Exception ex) {
            System.out.println(""+ex.getMessage());
        }
            if(txtCorreo.getText().isEmpty()||pass.isEmpty()){
                JOptionPane.showMessageDialog(this, "campos vacios ");
            }else{
                String rol="";
                System.out.println(txtCorreo.getText().trim()+" "+contra);
                if(usuarioBO.isLogin(txtCorreo.getText(),contra)){
                    JOptionPane.showMessageDialog(this, "Inicio de sesion exitoso");
                    user=usuarioBO.cargarUsuario(txtCorreo.getText().trim(),contra);
                    gestionClientes.setUser(user);
                    gestionEmpleados.setUser(user);
                    gestionUsuarios.setUser(user);
                    gestionServicios.setU(user);
                    System.out.println(user);
                    if(user.getUsu_rol()=='A'){
                        rol="Admin";
                    }else if(user.getUsu_rol()=='G'){
                        rol="Empleado";
                    }
                    ventanaPrincipal.getCerrarSesionJmenuItem().setVisible(true);
                    ventanaPrincipal.getIniciarSesionjMenuItem().setVisible(false);
                    ventanaPrincipal.getNameUserMenu().setText(rol+" "+user.getUsu_nombre());
                    if(user.getUsu_rol()=='A'){
                        ventanaPrincipal.getCitasMenu().setVisible(true);
                        ventanaPrincipal.getClientesMenu().setVisible(true);
                        ventanaPrincipal.getEmpleadosMenu().setVisible(true);
                        ventanaPrincipal.getFacturasMenu().setVisible(true);
                        ventanaPrincipal.getServiciosMenu().setVisible(true);
                        ventanaPrincipal.getUsuariosmenu().setVisible(true);
                        ventanaPrincipal.getNameUserMenu().setVisible(true);
                    }else{
                        ventanaPrincipal.getCitasMenu().setVisible(true);
                        ventanaPrincipal.getClientesMenu().setVisible(true);
                        ventanaPrincipal.getEmpleadosMenu().setVisible(false);
                        ventanaPrincipal.getFacturasMenu().setVisible(true);
                        ventanaPrincipal.getServiciosMenu().setVisible(true);
                        ventanaPrincipal.getUsuariosmenu().setVisible(false);
                        ventanaPrincipal.getNameUserMenu().setVisible(true);
                    }
                    
                    this.dispose();
                    Limpiar();
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Usuario o contrasena incorrecta ");
                    Limpiar();
                }
                
            }
      
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated
    public void Limpiar() {
        txtCorreo.setText("");
        txtPass.setText("");
    }

    public Usuarios getUser() {
        return user;
    }
    
 Map<Character, Character> map = new HashMap<>();


    private void cargarLetras() {
        map.put('a', '*');
        map.put('b', '$');
        map.put('c', '?');
        map.put('d', '%');
        map.put('e', '#');
        map.put('f', '!');
        map.put('g', '¡');
        map.put('h', '¿');
        map.put('i', '}');
        map.put('j', '{');
        map.put('k', '[');
        map.put('l', ']');
        map.put('m', '|');
        map.put('n', '°');
        map.put('ñ', '=');
        map.put('o', '+');
        map.put('p', '-');
        map.put('q', ';');
        map.put('r', ',');
        map.put('s', '>');
        map.put('t', '<');
        map.put('u', 'A');
        map.put('v', 'B');
        map.put('w', 'C');
        map.put('x', 'f');
        map.put('y', 'x');
        map.put('z', 'p');
        map.put(' ', 'd');
        map.put('A', '&');
        map.put('B', '0');
        map.put('C', '1');
        map.put('D', '2');
        map.put('E', '3');
        map.put('F', '4');
        map.put('G', '5');
        map.put('H', '6');
        map.put('I', '7');
        map.put('J', '8');
        map.put('K', '9');
        map.put('L', 'ñ');
        map.put('M', 'y');
        map.put('N', 'Y');
        map.put('Ñ', '♠');
        map.put('O', 'z');
        map.put('P', 'Z');
        map.put('Q', 'X');
        map.put('R', 'W');
        map.put('S', 'w');
        map.put('T', 'J');
        map.put('U', 'j');
        map.put('V', 'Ñ');
        map.put('W', 'g');
        map.put('X', 'G');
        map.put('Y', 'P');
        map.put('Z', 'F');

    }

   private void cargarNumeros() {
        map.put('1', 'v');
        map.put('2', '♦');
        map.put('3', 's');
        map.put('4', 'E');
        map.put('5', 'k');
        map.put('6', '@');
        map.put('7', '☻');
        map.put('8', '↑');
        map.put('9', '↨');
        map.put('0', 'a');
    }

    private String encript(String cadena) {
        String encript = "";
        cargarLetras();
        cargarNumeros();
        for (int i = 0; i < cadena.length(); i++) {
            for (Map.Entry<Character, Character> entry : map.entrySet()) {
                char c = cadena.charAt(i);
        
                if (c==entry.getValue()) {

                    encript += entry.getKey();

                }

            }
        }
        return encript;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables


}
